import { Property } from "@/types/property";

export const featuredProperties: Property[] = [
  {
    id: 1,
    userId: 1,
    title: "Căn hộ cao cấp The Gold View",
    slug: "can-ho-cao-cap-the-gold-view",
    categoryId: 1,
    price: 15000000,
    area: 85,
    bedrooms: 2,
    bathrooms: 2,
    viewCount: 512,
    direction: "Đông Nam",
    numFloors: 25,
    priorityStatus: "diamond", // Gói cao cấp nhất
    cityId: 1,
    districtId: 101,
    wardId: 1001,
    addressDetail: "123 Nguyễn Huệ, Quận 1",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    isFeatured: true,
    createdAt: "2024-12-01",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 101, cityId: 1, name: "Quận 1", slug: "quan-1" },
  },
  {
    id: 2,
    userId: 2,
    title: "Penthouse Landmark 81",
    slug: "penthouse-landmark-81",
    categoryId: 1,
    price: 35000000,
    area: 250,
    bedrooms: 4,
    bathrooms: 3,
    viewCount: 890,
    direction: "Tây Bắc",
    numFloors: 81,
    priorityStatus: "diamond",
    cityId: 1,
    districtId: 102,
    wardId: 1002,
    addressDetail: "208 Nguyễn Hữu Cảnh, Quận Bình Thạnh",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    isFeatured: true,
    createdAt: "2024-11-28",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 102, cityId: 1, name: "Bình Thạnh", slug: "binh-thanh" },
  },
  {
    id: 3,
    userId: 3,
    title: "Nhà phố Thảo Điền",
    slug: "nha-pho-thao-dien",
    categoryId: 2,
    price: 12000000,
    area: 120,
    bedrooms: 3,
    bathrooms: 3,
    viewCount: 425,
    direction: "Đông",
    numFloors: 4,
    priorityStatus: "vip",
    cityId: 1,
    districtId: 103,
    wardId: 1003,
    addressDetail: "45 Thảo Điền, Quận 2",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    isFeatured: true,
    createdAt: "2024-11-25",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 103, cityId: 1, name: "Quận 2", slug: "quan-2" },
  },
  {
    id: 4,
    userId: 4,
    title: "Căn hộ Vinhomes Central Park",
    slug: "can-ho-vinhomes-central-park",
    categoryId: 1,
    price: 8500000,
    area: 65,
    bedrooms: 1,
    bathrooms: 1,
    viewCount: 312,
    direction: "Tây",
    numFloors: 15,
    priorityStatus: "hot",
    cityId: 1,
    districtId: 104,
    wardId: 1004,
    addressDetail: "720A Điện Biên Phủ, Quận Bình Thạnh",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    isFeatured: true,
    createdAt: "2024-11-22",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 104, cityId: 1, name: "Bình Thạnh", slug: "binh-thanh" },
  },
  {
    id: 5,
    userId: 5,
    title: "Officetel Millennium",
    slug: "officetel-millennium",
    categoryId: 3,
    price: 5000000,
    area: 45,
    bedrooms: 1,
    bathrooms: 1,
    viewCount: 156,
    direction: "Bắc",
    numFloors: 20,
    priorityStatus: "normal",
    cityId: 1,
    districtId: 101,
    wardId: 1005,
    addressDetail: "132 Bến Vân Đồn, Quận 4",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    isFeatured: true,
    createdAt: "2024-11-20",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 101, cityId: 1, name: "Quận 1", slug: "quan-1" },
  },
  {
    id: 6,
    userId: 6,
    title: "Biệt thự khu compound Phú Mỹ Hưng",
    slug: "biet-thu-compound-phu-my-hung",
    categoryId: 2,
    price: 25000000,
    area: 180,
    bedrooms: 4,
    bathrooms: 4,
    viewCount: 678,
    direction: "Nam",
    numFloors: 2,
    priorityStatus: "diamond",
    cityId: 1,
    districtId: 105,
    wardId: 1006,
    addressDetail: "Đường Tôn Đức Thắng, Quận 7",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    isFeatured: true,
    createdAt: "2024-11-18",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 105, cityId: 1, name: "Quận 7", slug: "quan-7" },
  },
  {
    id: 7,
    userId: 7,
    title: "Căn hộ Ascent Lakeside",
    slug: "can-ho-ascent-lakeside",
    categoryId: 1,
    price: 6500000,
    area: 72,
    bedrooms: 2,
    bathrooms: 2,
    viewCount: 245,
    direction: "Tây Nam",
    numFloors: 12,
    priorityStatus: "vip",
    cityId: 1,
    districtId: 106,
    wardId: 1007,
    addressDetail: "Khu Eurovia, Quận 7",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    isFeatured: true,
    createdAt: "2024-11-15",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 106, cityId: 1, name: "Quận 7", slug: "quan-7" },
  },
  {
    id: 8,
    userId: 8,
    title: "Shophouse Saigon Pearl",
    slug: "shophouse-saigon-pearl",
    categoryId: 4,
    price: 18000000,
    area: 95,
    bedrooms: 0,
    bathrooms: 1,
    viewCount: 389,
    direction: "Đông Nam",
    numFloors: 2,
    priorityStatus: "hot",
    cityId: 1,
    districtId: 102,
    wardId: 1008,
    addressDetail: "92 Nguyễn Hữu Cảnh, Bình Thạnh",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    isFeatured: true,
    createdAt: "2024-11-12",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 102, cityId: 1, name: "Bình Thạnh", slug: "binh-thanh" },
  },
];
