import { Property } from "@/types/property";
import { Category } from "@/types/category";
import { Post } from "@/types/post";

export const mockCategories: Category[] = [
  {
    id: 1,
    parentId: null,
    name: "Cho thuê",
    slug: "cho-thue",
    fullPath: "cho-thue",
    priority: 1,
    isActive: true,
    createdAt: "2026-05-07T07:58:04.000Z",
    updatedAt: "2026-05-07T07:58:04.000Z",
    children: [
      {
        id: 2,
        parentId: 1,
        name: "Văn phòng",
        slug: "van-phong",
        fullPath: "cho-thue/van-phong",
        priority: 1,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 3,
        parentId: 1,
        name: "Mặt bằng",
        slug: "mat-bang",
        fullPath: "cho-thue/mat-bang",
        priority: 2,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 4,
        parentId: 1,
        name: "Kho xưởng",
        slug: "kho-xuong",
        fullPath: "cho-thue/kho-xuong",
        priority: 3,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 5,
        parentId: 1,
        name: "Khu công nghiệp",
        slug: "khu-cong-nghiep",
        fullPath: "cho-thue/khu-cong-nghiep",
        priority: 4,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 6,
        parentId: 1,
        name: "Căn hộ, chung cư",
        slug: "can-ho-chung-cu",
        fullPath: "cho-thue/can-ho-chung-cu",
        priority: 5,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 7,
        parentId: 1,
        name: "Trung tâm thương mại",
        slug: "trung-tam-thuong-mai",
        fullPath: "cho-thue/trung-tam-thuong-mai",
        priority: 6,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 8,
        parentId: 1,
        name: "Nhà trọ, phòng trọ",
        slug: "nha-tro-phong-tro",
        fullPath: "cho-thue/nha-tro-phong-tro",
        priority: 7,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
    ],
  },
  {
    id: 9,
    parentId: null,
    name: "Cần thuê",
    slug: "can-thue",
    fullPath: "can-thue",
    priority: 2,
    isActive: true,
    createdAt: "2026-05-07T07:58:04.000Z",
    updatedAt: "2026-05-07T07:58:04.000Z",
    children: [
      {
        id: 10,
        parentId: 9,
        name: "Văn phòng",
        slug: "van-phong",
        fullPath: "can-thue/van-phong",
        priority: 1,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 11,
        parentId: 9,
        name: "Mặt bằng",
        slug: "mat-bang",
        fullPath: "can-thue/mat-bang",
        priority: 2,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 12,
        parentId: 9,
        name: "Kho xưởng",
        slug: "kho-xuong",
        fullPath: "can-thue/kho-xuong",
        priority: 3,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 13,
        parentId: 9,
        name: "Khu công nghiệp",
        slug: "khu-cong-nghiep",
        fullPath: "can-thue/khu-cong-nghiep",
        priority: 4,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 14,
        parentId: 9,
        name: "Căn hộ, chung cư",
        slug: "can-ho-chung-cu",
        fullPath: "can-thue/can-ho-chung-cu",
        priority: 5,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 15,
        parentId: 9,
        name: "Trung tâm thương mại",
        slug: "trung-tam-thuong-mai",
        fullPath: "can-thue/trung-tam-thuong-mai",
        priority: 6,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 16,
        parentId: 9,
        name: "Nhà trọ, phòng trọ",
        slug: "nha-tro-phong-tro",
        fullPath: "can-thue/nha-tro-phong-tro",
        priority: 7,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
    ],
  },
  {
    id: 17,
    parentId: null,
    name: "Dự án",
    slug: "du-an",
    fullPath: "du-an",
    priority: 3,
    isActive: true,
    createdAt: "2026-05-07T07:58:04.000Z",
    updatedAt: "2026-05-07T07:58:04.000Z",
    children: [],
  },
  {
    id: 18,
    parentId: null,
    name: "Tin tức",
    slug: "tin-tuc",
    fullPath: "tin-tuc",
    priority: 4,
    isActive: true,
    createdAt: "2026-05-07T07:58:04.000Z",
    updatedAt: "2026-05-07T07:58:04.000Z",
    children: [
      {
        id: 19,
        parentId: 18,
        name: "Kiến trúc xây dựng",
        slug: "kien-truc-xay-dung",
        fullPath: "tin-tuc/kien-truc-xay-dung",
        priority: 1,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 20,
        parentId: 18,
        name: "Tư vấn luật",
        slug: "tu-van-luat",
        fullPath: "tin-tuc/tu-van-luat",
        priority: 2,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
      {
        id: 21,
        parentId: 18,
        name: "Phong thủy",
        slug: "phong-thuy",
        fullPath: "tin-tuc/phong-thuy",
        priority: 3,
        isActive: true,
        createdAt: "2026-05-07T07:58:04.000Z",
        updatedAt: "2026-05-07T07:58:04.000Z",
      },
    ],
  },
];

export const mockPosts: Post[] = [
  {
    id: 1,
    categoryId: 19,
    title: "SHIN CÀ PHÊ - ĐÔNG HÀNH CÙNG BẠN CHINH PHỤC DALAT ULTRA TRAIL 2026",
    slug: "shin-ca-phe-dong-hanh-dalat-ultra-trail-2026",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    summary:
      "Đã Lạt tháng 3 – khi những làn sương mờ còn bằng lắng trên định Langbiang cùng là lúc nhịp đập của hàng ngàn 'chiến binh' được chạy dạng thôn thức. Bạn đã sẵn sàng không?",
    content:
      "Đã Lạt tháng 3 – khi những làn sương mờ còn bằng lắng trên định Langbiang cùng là lúc nhịp đập của hàng ngàn 'chiến binh' được chạy dạng thôn thức.",
    viewCount: 245,
    status: "published",
    isFeatured: true,
    createdAt: "2026-04-13",
    category: {
      id: 19,
      name: "Kiến trúc xây dựng",
      slug: "kien-truc-xay-dung",
    },
  },
  {
    id: 2,
    categoryId: 20,
    title:
      "ISOUP HUUPSI, ICHILL & IKIRO HẬN HÀNH ĐÔNG HÀNH CÙNG DALAT ULTRA TRAIL 2026",
    slug: "isoup-ichill-ikiro-dalat-ultra-trail",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    summary:
      "Đã Lạt tháng 4 – khi những trận mưa nhẹ rơi trên những con đường núi, là lúc các thương hiệu nổi tiếng quy tụ để hỗ trợ những runner.",
    content:
      "Đã Lạt tháng 4 – khi những trận mưa nhẹ rơi trên những con đường núi...",
    viewCount: 189,
    status: "published",
    isFeatured: false,
    createdAt: "2026-04-07",
    category: { id: 20, name: "Tư vấn luật", slug: "tu-van-luat" },
  },
  {
    id: 3,
    categoryId: 19,
    title: "Kinh nghiệm thuê mặt bằng kinh doanh cho người mới bắt đầu",
    slug: "kinh-nghiem-thue-mat-bang-kinh-doanh",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    summary:
      "Kinh nghiệm thuê mặt bằng kinh doanh cho người mới giúp tránh những sai lầm lớn, chọn đúng vị trí, tối ưu chi phí và nâng cao doanh thu.",
    content: "Kinh nghiệm thuê mặt bằng kinh doanh cho người mới...",
    viewCount: 156,
    status: "published",
    isFeatured: false,
    createdAt: "2026-04-05",
    category: {
      id: 19,
      name: "Kiến trúc xây dựng",
      slug: "kien-truc-xay-dung",
    },
  },
  {
    id: 4,
    categoryId: 21,
    title: "Checklist thuê mặt bằng mở quán cafe tại TP.HCM cho người mới",
    slug: "checklist-thue-mat-bang-cafe-tphcm",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    summary:
      "Checklist thuê mặt bằng mở quán cafe tại TP.HCM từ A-Z: cách chọn vị trí, tính chi phí, xem hợp đồng và những lưu ý khác.",
    content: "Checklist thuê mặt bằng mở quán cafe tại TP.HCM...",
    viewCount: 203,
    status: "published",
    isFeatured: false,
    createdAt: "2026-04-06",
    category: { id: 21, name: "Phong thủy", slug: "phong-thuy" },
  },
];

export const featuredProperties: Property[] = [
  // --- Gold (6 items) ---
  {
    id: 1,
    userId: 1,
    title: "Căn hộ cao cấp The Gold View",
    slug: "can-ho-cao-cap-the-gold-view",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 15000000,
    area: 85,
    bedrooms: 2,
    bathrooms: 2,
    viewCount: 512,
    direction: "Đông Nam",
    numFloors: 25,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 101,
    wardId: 1001,
    addressDetail: "123 Nguyễn Huệ, Quận 1",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Căn hộ cao cấp, vị trí trung tâm Quận 1, tiện nghi đầy đủ.",
    isFeatured: true,
    createdAt: "2024-12-01",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 101, cityId: 1, name: "Quận 1", slug: "quan-1" },
  },
  {
    id: 2,
    userId: 2,
    title: "Penthouse Landmark 81",
    slug: "penthouse-landmark-81",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 35000000,
    area: 250,
    bedrooms: 4,
    bathrooms: 3,
    viewCount: 890,
    direction: "Tây Bắc",
    numFloors: 81,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 102,
    wardId: 1002,
    addressDetail: "208 Nguyễn Hữu Cảnh, Quận Bình Thạnh",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description:
      "Penthouse sang trọng tại Landmark 81 với tầm nhìn toàn thành phố.",
    isFeatured: true,
    createdAt: "2024-11-28",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 102, cityId: 1, name: "Bình Thạnh", slug: "binh-thanh" },
  },
  {
    id: 9,
    userId: 9,
    title: "Villa Rivieria Quận 2",
    slug: "villa-rivieria-quan-2",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 45000000,
    area: 350,
    bedrooms: 5,
    bathrooms: 5,
    viewCount: 1200,
    direction: "Nam",
    numFloors: 3,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 103,
    wardId: 1009,
    addressDetail: "Đường Giang Văn Minh, An Phú, Quận 2",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Biệt thự ven sông đẳng cấp, có hồ bơi riêng và sân vườn.",
    isFeatured: true,
    createdAt: "2024-12-05",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 103, cityId: 1, name: "Quận 2", slug: "quan-2" },
  },
  {
    id: 10,
    userId: 10,
    title: "Căn hộ Serenity Sky Villas",
    slug: "can-ho-serenity-sky-villas",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 28000000,
    area: 150,
    bedrooms: 3,
    bathrooms: 3,
    viewCount: 750,
    direction: "Đông Bắc",
    numFloors: 15,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 107,
    wardId: 1010,
    addressDetail: "259 Điện Biên Phủ, Quận 3",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description:
      "Biệt thự trên không giữa lòng Quận 3, thiết kế cực kỳ hiện đại.",
    isFeatured: true,
    createdAt: "2024-12-03",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 107, cityId: 1, name: "Quận 3", slug: "quan-3" },
  },
  {
    id: 11,
    userId: 11,
    title: "Văn phòng hạng A Bitexco Tower",
    slug: "van-phong-hang-a-bitexco",
    categoryId: 10,
    category: { id: 10, slug: "van-phong", name: "Văn phòng" },
    price: 55000000,
    area: 500,
    bedrooms: 0,
    bathrooms: 4,
    viewCount: 1100,
    direction: "Tây Nam",
    numFloors: 68,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 101,
    wardId: 1001,
    addressDetail: "2 Hải Triều, Bến Nghé, Quận 1",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Văn phòng làm việc chuyên nghiệp, tầm nhìn bao quát Sài Gòn.",
    isFeatured: true,
    createdAt: "2024-12-07",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 101, cityId: 1, name: "Quận 1", slug: "quan-1" },
  },
  {
    id: 12,
    userId: 12,
    title: "Dinh thự Chateau Phú Mỹ Hưng",
    slug: "dinh-thu-chateau-phu-my-hung",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 60000000,
    area: 600,
    bedrooms: 6,
    bathrooms: 7,
    viewCount: 920,
    direction: "Nam",
    numFloors: 3,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 105,
    wardId: 1006,
    addressDetail: "Khu Chateau, Phú Mỹ Hưng, Quận 7",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description: "Dinh thự siêu sang trọng, cộng đồng cư dân tinh hoa.",
    isFeatured: true,
    createdAt: "2024-12-10",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 105, cityId: 1, name: "Quận 7", slug: "quan-7" },
  },

  // --- GOLD (6 items) ---
  {
    id: 3,
    userId: 3,
    title: "Nhà phố Thảo Điền",
    slug: "nha-pho-thao-dien",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 12000000,
    area: 120,
    bedrooms: 3,
    bathrooms: 3,
    viewCount: 425,
    direction: "Đông",
    numFloors: 4,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 103,
    wardId: 1003,
    addressDetail: "45 Thảo Điền, Quận 2",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Nhà phố cao cấp tại Thảo Điền, không gian sống rộng rãi.",
    isFeatured: true,
    createdAt: "2024-11-25",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 103, cityId: 1, name: "Quận 2", slug: "quan-2" },
  },
  {
    id: 4,
    userId: 4,
    title: "Căn hộ Vinhomes Central Park",
    slug: "can-ho-vinhomes-central-park",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 8500000,
    area: 65,
    bedrooms: 1,
    bathrooms: 1,
    viewCount: 312,
    direction: "Tây",
    numFloors: 15,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 104,
    wardId: 1004,
    addressDetail: "720A Điện Biên Phủ, Quận Bình Thạnh",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description: "Căn hộ tại Vinhomes Central Park, tiện ích cộng đồng đầy đủ.",
    isFeatured: true,
    createdAt: "2024-11-22",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 104, cityId: 1, name: "Bình Thạnh", slug: "binh-thanh" },
  },
  {
    id: 13,
    userId: 13,
    title: "Căn hộ Masteri Thảo Điền",
    slug: "can-ho-masteri-thao-dien",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 9000000,
    area: 75,
    bedrooms: 2,
    bathrooms: 2,
    viewCount: 410,
    direction: "Đông",
    numFloors: 30,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 103,
    wardId: 1003,
    addressDetail: "159 Xa lộ Hà Nội, Quận 2",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Căn hộ hiện đại, kết nối trực tiếp với tuyến Metro.",
    isFeatured: true,
    createdAt: "2024-12-02",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 103, cityId: 1, name: "Quận 2", slug: "quan-2" },
  },
  {
    id: 14,
    userId: 14,
    title: "Nhà phố Sun City Quận 9",
    slug: "nha-pho-sun-city-quan-9",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 7500000,
    area: 100,
    bedrooms: 3,
    bathrooms: 2,
    viewCount: 280,
    direction: "Bắc",
    numFloors: 2,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 108,
    wardId: 1014,
    addressDetail: "Đường Liên Phường, Quận 9",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description: "Khu dân cư an ninh, yên tĩnh, phù hợp cho gia đình trẻ.",
    isFeatured: true,
    createdAt: "2024-11-30",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 108, cityId: 1, name: "Quận 9", slug: "quan-9" },
  },
  {
    id: 15,
    userId: 15,
    title: "Căn hộ Estella Heights",
    slug: "can-ho-estella-heights",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 18000000,
    area: 105,
    bedrooms: 2,
    bathrooms: 2,
    viewCount: 620,
    direction: "Đông Nam",
    numFloors: 35,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 103,
    wardId: 1003,
    addressDetail: "88 Song Hành, Quận 2",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Căn hộ nghỉ dưỡng với tiện ích resort 5 sao.",
    isFeatured: true,
    createdAt: "2024-12-04",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 103, cityId: 1, name: "Quận 2", slug: "quan-2" },
  },
  {
    id: 16,
    userId: 16,
    title: "Shophouse Lakeview City",
    slug: "shophouse-lakeview-city",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 14000000,
    area: 110,
    bedrooms: 0,
    bathrooms: 2,
    viewCount: 340,
    direction: "Nam",
    numFloors: 4,
    priorityStatus: "gold",
    cityId: 1,
    districtId: 103,
    wardId: 1016,
    addressDetail: "Đường song hành cao tốc, Quận 2",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description:
      "Shophouse mặt tiền lớn, thích hợp mở văn phòng hoặc kinh doanh.",
    isFeatured: true,
    createdAt: "2024-11-26",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 103, cityId: 1, name: "Quận 2", slug: "quan-2" },
  },

  // --- SILVER (6 items) ---
  {
    id: 5,
    userId: 5,
    title: "Officetel Millennium",
    slug: "officetel-millennium",
    categoryId: 10,
    category: { id: 10, slug: "van-phong", name: "Văn phòng" },
    price: 5000000,
    area: 45,
    bedrooms: 1,
    bathrooms: 1,
    viewCount: 156,
    direction: "Bắc",
    numFloors: 20,
    priorityStatus: "silver",
    cityId: 1,
    districtId: 101,
    wardId: 1005,
    addressDetail: "132 Bến Vân Đồn, Quận 4",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Officetel phù hợp cho doanh nghiệp nhỏ.",
    isFeatured: true,
    createdAt: "2024-11-20",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 101, cityId: 1, name: "Quận 1", slug: "quan-1" },
  },
  {
    id: 6,
    userId: 6,
    title: "Biệt thự khu compound Phú Mỹ Hưng",
    slug: "biet-thu-compound-phu-my-hung",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 25000000,
    area: 180,
    bedrooms: 4,
    bathrooms: 4,
    viewCount: 678,
    direction: "Nam",
    numFloors: 2,
    priorityStatus: "silver",
    cityId: 1,
    districtId: 105,
    wardId: 1006,
    addressDetail: "Đường Tôn Đức Thắng, Quận 7",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description: "Biệt thự trong compound, an ninh tốt, sân vườn riêng.",
    isFeatured: true,
    createdAt: "2024-11-18",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 105, cityId: 1, name: "Quận 7", slug: "quan-7" },
  },
  {
    id: 17,
    userId: 17,
    title: "Căn hộ Flora Fuji Quận 9",
    slug: "can-ho-flora-fuji-quan-9",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 4500000,
    area: 54,
    bedrooms: 1,
    bathrooms: 1,
    viewCount: 210,
    direction: "Đông",
    numFloors: 10,
    priorityStatus: "silver",
    cityId: 1,
    districtId: 108,
    wardId: 1017,
    addressDetail: "Đường Phước Hữu, Quận 9",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Căn hộ chuẩn Nhật, thiết kế tối ưu, không gian xanh.",
    isFeatured: true,
    createdAt: "2024-11-14",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 108, cityId: 1, name: "Quận 9", slug: "quan-9" },
  },
  {
    id: 18,
    userId: 18,
    title: "Văn phòng ảo REE Tower",
    slug: "van-phong-ao-ree-tower",
    categoryId: 10,
    category: { id: 10, slug: "van-phong", name: "Văn phòng" },
    price: 3000000,
    area: 20,
    bedrooms: 0,
    bathrooms: 1,
    viewCount: 180,
    direction: "Bắc",
    numFloors: 21,
    priorityStatus: "silver",
    cityId: 1,
    districtId: 109,
    wardId: 1018,
    addressDetail: "9 Đoàn Văn Bơ, Quận 4",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description: "Không gian làm việc chung, đầy đủ thiết bị văn phòng.",
    isFeatured: true,
    createdAt: "2024-11-10",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 109, cityId: 1, name: "Quận 4", slug: "quan-4" },
  },
  {
    id: 19,
    userId: 19,
    title: "Căn hộ Citihome Cát Lái",
    slug: "can-ho-citihome-cat-lai",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 3800000,
    area: 60,
    bedrooms: 2,
    bathrooms: 2,
    viewCount: 195,
    direction: "Tây",
    numFloors: 18,
    priorityStatus: "silver",
    cityId: 1,
    districtId: 103,
    wardId: 1019,
    addressDetail: "Khu đô thị Cát Lái, Quận 2",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Căn hộ giá tốt, dân cư đông đúc, gần trường học.",
    isFeatured: true,
    createdAt: "2024-11-08",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 103, cityId: 1, name: "Quận 2", slug: "quan-2" },
  },
  {
    id: 20,
    userId: 20,
    title: "Nhà phố liền kề Khang Điền",
    slug: "nha-pho-khang-dien-quan-9",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 9500000,
    area: 90,
    bedrooms: 3,
    bathrooms: 3,
    viewCount: 310,
    direction: "Đông Bắc",
    numFloors: 3,
    priorityStatus: "silver",
    cityId: 1,
    districtId: 108,
    wardId: 1020,
    addressDetail: "Võ Chí Công, Quận 9",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description: "Nhà xây sẵn, thiết kế đồng bộ, tiện ích nội khu đa dạng.",
    isFeatured: true,
    createdAt: "2024-11-05",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 108, cityId: 1, name: "Quận 9", slug: "quan-9" },
  },

  // --- NORMAL (6 items) ---
  {
    id: 7,
    userId: 7,
    title: "Căn hộ Ascent Lakeside",
    slug: "can-ho-ascent-lakeside",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 6500000,
    area: 72,
    bedrooms: 2,
    bathrooms: 2,
    viewCount: 245,
    direction: "Tây Nam",
    numFloors: 12,
    priorityStatus: "normal",
    cityId: 1,
    districtId: 106,
    wardId: 1007,
    addressDetail: "Khu Eurovia, Quận 7",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Căn hộ Ascent Lakeside, thiết kế hiện đại.",
    isFeatured: true,
    createdAt: "2024-11-15",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 106, cityId: 1, name: "Quận 7", slug: "quan-7" },
  },
  {
    id: 8,
    userId: 8,
    title: "Shophouse Saigon Pearl",
    slug: "shophouse-saigon-pearl",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 18000000,
    area: 95,
    bedrooms: 0,
    bathrooms: 1,
    viewCount: 389,
    direction: "Đông Nam",
    numFloors: 2,
    priorityStatus: "normal",
    cityId: 1,
    districtId: 102,
    wardId: 1008,
    addressDetail: "92 Nguyễn Hữu Cảnh, Bình Thạnh",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description: "Shophouse tại Saigon Pearl phù hợp kinh doanh.",
    isFeatured: true,
    createdAt: "2024-11-12",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 102, cityId: 1, name: "Bình Thạnh", slug: "binh-thanh" },
  },
  {
    id: 21,
    userId: 21,
    title: "Phòng trọ cao cấp Tân Bình",
    slug: "phong-tro-cao-cap-tan-binh",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 3500000,
    area: 25,
    bedrooms: 1,
    bathrooms: 1,
    viewCount: 120,
    direction: "Nam",
    numFloors: 5,
    priorityStatus: "normal",
    cityId: 1,
    districtId: 110,
    wardId: 1021,
    addressDetail: "Phạm Văn Hai, Tân Bình",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Phòng trọ đầy đủ tiện nghi, giờ giấc tự do.",
    isFeatured: true,
    createdAt: "2024-11-01",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 110, cityId: 1, name: "Tân Bình", slug: "tan-binh" },
  },
  {
    id: 22,
    userId: 22,
    title: "Mặt bằng kinh doanh Gò Vấp",
    slug: "mat-bang-kinh-doanh-go-vap",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 12000000,
    area: 60,
    bedrooms: 0,
    bathrooms: 1,
    viewCount: 260,
    direction: "Tây",
    numFloors: 1,
    priorityStatus: "normal",
    cityId: 1,
    districtId: 111,
    wardId: 1022,
    addressDetail: "Quang Trung, Gò Vấp",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description: "Mặt bằng rộng, khu vực sầm uất, thuận tiện buôn bán.",
    isFeatured: true,
    createdAt: "2024-10-25",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 111, cityId: 1, name: "Gò Vấp", slug: "go-vap" },
  },
  {
    id: 23,
    userId: 23,
    title: "Căn hộ Ehome S Quận 9",
    slug: "can-ho-ehome-s-quan-9",
    categoryId: 14,
    category: { id: 14, slug: "can-ho-chung-cu", name: "Căn hộ, chung cư" },
    price: 3200000,
    area: 40,
    bedrooms: 1,
    bathrooms: 1,
    viewCount: 150,
    direction: "Bắc",
    numFloors: 12,
    priorityStatus: "normal",
    cityId: 1,
    districtId: 108,
    wardId: 1023,
    addressDetail: "Khu dân cư Nam Long, Quận 9",
    thumbnailUrl: "/imgs/wallpaper-1.jpg",
    status: "published",
    description: "Căn hộ giá rẻ cho người thu nhập thấp.",
    isFeatured: true,
    createdAt: "2024-10-20",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 108, cityId: 1, name: "Quận 9", slug: "quan-9" },
  },
  {
    id: 24,
    userId: 24,
    title: "Nhà nguyên căn Hóc Môn",
    slug: "nha-nguyen-can-hoc-mon",
    categoryId: 11,
    category: { id: 11, slug: "mat-bang", name: "Mặt bằng" },
    price: 4000000,
    area: 80,
    bedrooms: 2,
    bathrooms: 1,
    viewCount: 95,
    direction: "Đông",
    numFloors: 1,
    priorityStatus: "normal",
    cityId: 1,
    districtId: 112,
    wardId: 1024,
    addressDetail: "Xã Bà Điểm, Hóc Môn",
    thumbnailUrl: "/imgs/wallpaper-2.jpg",
    status: "published",
    description: "Nhà rộng rãi, thoáng mát, phù hợp gia đình ở lâu dài.",
    isFeatured: true,
    createdAt: "2024-10-15",
    city: { id: 1, name: "TP. Hồ Chí Minh", slug: "ho-chi-minh" },
    district: { id: 112, cityId: 1, name: "Hóc Môn", slug: "hoc-mon" },
  },
];

export const contentSEO = {
  title: "Cho Thuê Mặt Bằng, Văn Phòng, Kho Xưởng Uy Tín - Thuematbang.com.vn",
  description:
    "Thuematbang.com.vn - Kênh thông tin số 1 về cho thuê bất động sản. Hỗ trợ tìm kiếm mặt bằng kinh doanh, văn phòng, kho xưởng chính xác, hiệu quả và pháp lý đảm bảo.",
  content: `
    <p>Bên cạnh các hoạt động giao dịch nhà đất, thị trường <strong>cho thuê bất động sản</strong> đang diễn ra cực kỳ năng động trên toàn quốc. Bắt kịp xu hướng này, <strong>Thuematbang.com.vn</strong> tự hào là đơn vị dẫn đầu, hỗ trợ kết nối hàng ngàn tin rao <em>cho thuê văn phòng, mặt bằng, kho xưởng, căn hộ - chung cư</em> chất lượng và hiệu quả nhất hiện nay.</p>
    
    <p>Với lợi thế đi đầu về công nghệ kỹ thuật số và chất lượng tin bài, chúng tôi được đánh giá là "cầu nối" uy tín giúp khách hàng tìm kiếm bất động sản nhanh chóng. Mọi thông tin đều được sàng lọc chính xác, đi kèm hình ảnh chân thật và đảm bảo tính pháp lý nghiêm ngặt.</p>

    <h2>1. Đa dạng loại hình bất động sản cho thuê hot nhất</h2>
    <p>Nguồn cung <strong>bất động sản nhà đất cho thuê</strong> tại Việt Nam rất phong phú, đáp ứng trọn vẹn thị hiếu từ các doanh nghiệp đến cá nhân:</p>
    <ul>
      <li><strong>Cho thuê văn phòng:</strong> Nhiều diện tích linh hoạt tại các tòa nhà hạng A, B, C.</li>
      <li><strong>Cho thuê mặt bằng:</strong> Vị trí đắc địa, thuận tiện cho mọi ngành nghề kinh doanh.</li>
      <li><strong>Kho xưởng cho thuê:</strong> Hệ thống bãi kho chuẩn quy hoạch, giao thông thuận lợi.</li>
      <li><strong>Căn hộ - Chung cư:</strong> Đầy đủ phân khúc từ bình dân đến cao cấp.</li>
    </ul>

    <h2>2. Sức hút từ bất động sản mặt tiền cho thuê</h2>
    <p>Nhà mặt tiền luôn là "phân khúc nóng" nhờ vị trí đắc địa, là lựa chọn hàng đầu để mở quán cafe, văn phòng giao dịch hoặc showroom. Giá <strong>cho thuê nhà mặt tiền</strong> có biên độ rộng từ vài chục đến hàng trăm triệu đồng mỗi tháng, tùy thuộc vào vị trí và hạ tầng khu vực.</p>
    <p>Chúng tôi cam kết hỗ trợ tối đa để khách thuê tìm được vị trí "đúng ý", giúp khởi tạo lợi thế cạnh tranh ngay từ bước đầu chọn mặt bằng.</p>

    <h2>3. Tư vấn trọn gói dịch vụ văn phòng cho thuê</h2>
    <p>Thuematbang.com.vn hiểu rõ những khó khăn của doanh nghiệp khi tìm kiếm không gian làm việc. Chúng tôi không chỉ cung cấp tin rao mà còn mang đến giải pháp tư vấn toàn diện, giúp quảng bá sản phẩm và kết nối các đối tác <strong>cho thuê văn phòng</strong> một cách chuyên nghiệp và chu đáo nhất.</p>

    <h2>4. Nguồn cung dồi dào về kho xưởng và trung tâm thương mại</h2>
    <p>Đối với doanh nghiệp sản xuất, <strong>kho xưởng</strong> là yếu tố sống còn. Kho xưởng cần đáp ứng các tiêu chuẩn về diện tích, công năng và vị trí trung chuyển. Ngoài ra, các phân khúc khác như <em>trung tâm thương mại, nhà trọ, phòng trọ</em> cũng được chúng tôi phủ sóng rộng khắp các quận huyện tại TP. Hồ Chí Minh và các tỉnh thành lân cận.</p>

    <h2>5. Đội ngũ nhân viên chuyên nghiệp và tận tâm</h2>
    <p>Với nhiều năm kinh nghiệm trong ngành, đội ngũ nhân sự của chúng tôi luôn được đào tạo bài bản để hỗ trợ khách hàng sàng lọc thông tin <strong>mặt bằng cho thuê chính xác</strong> nhất. Sự an tâm của khách hàng về chất lượng và tiện ích dịch vụ chính là kim chỉ nam cho sự phát triển bền vững của Thuematbang.com.vn.</p>

    <div className="bg-blue-50 p-6 rounded-xl border-l-4 border-blue-600 mt-8">
      <h3 className="text-xl font-bold mb-2">Liên hệ tìm kiếm mặt bằng ngay!</h3>
      <p>Thuê mặt bằng sẽ không còn là nỗi lo. Hãy để chúng tôi đồng hành cùng sự phát triển của bạn.</p>
      <p><strong>Hotline:</strong> 0968.68.80.81</p>
      <p><strong>Website:</strong> <a href="https://thuematbang.com.vn" className="text-blue-700 underline">Thuematbang.com.vn</a></p>
    </div>
  `,
};

export const faqs = [
  {
    id: "item-1",
    question: "Làm thế nào để tôi có thể đăng tin cho thuê mặt bằng?",
    answer:
      "Bạn chỉ cần đăng ký tài khoản, chọn mục 'Đăng tin' và điền đầy đủ các thông tin chi tiết về diện tích, vị trí, giá cả cùng hình ảnh thực tế của mặt bằng.",
  },
  {
    id: "item-2",
    question: "Chi phí đăng tin trên Thuematbang.com.vn là bao nhiêu?",
    answer:
      "Chúng tôi cung cấp nhiều gói đăng tin từ miễn phí đến các gói VIP có trả phí để tăng khả năng tiếp cận khách hàng mục tiêu hiệu quả hơn.",
  },
  {
    id: "item-3",
    question: "Tin đăng của tôi sẽ hiển thị trong bao lâu?",
    answer:
      "Tùy vào gói dịch vụ bạn chọn, tin đăng có thể hiển thị từ 7 ngày, 15 ngày hoặc cho đến khi mặt bằng đã được cho thuê thành công.",
  },
];
