export const ANALYTICS_EVENTS = {
  clickPostProperty: "click_post_property",
  propertyFormStarted: "property_form_started",
  propertyFormSubmitClicked: "property_form_submit_clicked",
  propertyFormCompleted: "property_form_completed",
  propertyFormFailed: "property_form_failed",
  clickPostRentRequest: "click_post_rent_request",
  rentRequestFormStarted: "rent_request_form_started",
  rentRequestFormSubmitClicked: "rent_request_form_submit_clicked",
  rentRequestFormCompleted: "rent_request_form_completed",
  rentRequestFormFailed: "rent_request_form_failed",
  clickPropertyListing: "click_property_listing",
  viewPropertyDetail: "view_property_detail",
  clickRentRequestListing: "click_rent_request_listing",
  viewRentRequestDetail: "view_rent_request_detail",
  clickProjectListing: "click_project_listing",
  viewProjectDetail: "view_project_detail",
  clickNewsListing: "click_news_listing",
  viewNewsDetail: "view_news_detail",
  clickContact: "click_contact",
  contactFormSubmitClicked: "contact_form_submit_clicked",
  contactFormCompleted: "contact_form_completed",
  contactFormFailed: "contact_form_failed",
  favoriteListing: "favorite_listing",
  unfavoriteListing: "unfavorite_listing",
  loginSubmitClicked: "login_submit_clicked",
  loginCompleted: "login_completed",
  loginFailed: "login_failed",
  googleLoginClicked: "google_login_clicked",
  registerSubmitClicked: "register_submit_clicked",
  registerCompleted: "register_completed",
  registerFailed: "register_failed",
  logoutClicked: "logout_clicked",
  logoutCompleted: "logout_completed",
  logoutFailed: "logout_failed",
  listingGalleryOpened: "listing_gallery_opened",
} as const;

export type AnalyticsEventName =
  (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
