function stamp() {
  return new Date().toISOString();
}

function createInitialState() {
  const seedProvinces = [
    { id: 1, name: "Hồ Chí Minh", slug: "tp-ho-chi-minh" },
    { id: 2, name: "Hà Nội", slug: "tp-ha-noi" },
  ];

  const seedWards = [
    { id: 11, provinceId: 1, name: "Quận 1", slug: "phuong-ben-nghe" },
    { id: 12, provinceId: 1, name: "Quận 7", slug: "phuong-tan-phong" },
    { id: 21, provinceId: 2, name: "Ba Đình", slug: "phuong-ba-dinh" },
  ];

  return {
    nextUserId: 3,
    nextPropertyId: 3,
    nextRentRequestId: 3,
    users: [
      {
        id: 1,
        fullName: "Test Customer",
        email: "customer@example.com",
        phone: "0901000001",
        role: "CUSTOMER",
        createdAt: stamp(),
        updatedAt: stamp(),
      },
      {
        id: 2,
        fullName: "Test Admin",
        email: "admin@example.com",
        phone: "0901000002",
        role: "ADMIN",
        createdAt: stamp(),
        updatedAt: stamp(),
      },
    ],
    tokens: new Map(),
    refreshTokens: new Map(),
    categories: [
      {
        id: 11,
        type: "PROPERTY",
        name: "Văn phòng",
        slug: "van-phong",
        priority: 1,
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
      {
        id: 12,
        type: "PROPERTY",
        name: "Mặt bằng",
        slug: "mat-bang",
        priority: 2,
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
      {
        id: 21,
        type: "RENT_REQUEST",
        name: "Căn hộ chung cư",
        slug: "can-ho-chung-cu",
        priority: 1,
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
      {
        id: 22,
        type: "RENT_REQUEST",
        name: "Văn phòng",
        slug: "van-phong",
        priority: 2,
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
      {
        id: 31,
        type: "NEWS",
        name: "Tin tức",
        slug: "tin-tuc",
        priority: 1,
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
    ],
    news: [
      {
        id: 1,
        categoryId: 31,
        category: {
          id: 31,
          type: "NEWS",
          name: "Tin tức",
          slug: "tin-tuc",
        },
        title: "Tin demo 1",
        slug: "tin-demo-1",
        excerpt: "Bai viet demo cho trang chu.",
        content: "Noi dung demo 1",
        thumbnailUrl: "/imgs/wallpaper-1.jpg",
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
      {
        id: 2,
        categoryId: 31,
        category: {
          id: 31,
          type: "NEWS",
          name: "Tin tức",
          slug: "tin-tuc",
        },
        title: "Tin demo 2",
        slug: "tin-demo-2",
        excerpt: "Bai viet demo so 2.",
        content: "Noi dung demo 2",
        thumbnailUrl: "/imgs/wallpaper-2.jpg",
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
    ],
    banners: [
      {
        id: 1,
        page: "home",
        imageUrl: "/imgs/wallpaper-2.jpg",
        mobileImageUrl: "/imgs/wallpaper-1.jpg",
        linkUrl: "/",
        title: "Banner home demo",
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
    ],
    faqs: [
      {
        id: 1,
        question: "Câu hỏi demo 1?",
        answer: "Câu trả lời demo 1.",
        page: "home",
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
      {
        id: 2,
        question: "Câu hỏi demo 2?",
        answer: "Câu trả lời demo 2.",
        page: "home",
        isActive: true,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
    ],
    seoContents: [
      {
        id: 1,
        page: "home",
        title: "Trang chủ demo",
        description: "Mo ta SEO demo cho trang chu.",
        keywords: "demo,home",
        createdAt: stamp(),
        updatedAt: stamp(),
      },
    ],
    leads: [
      {
        id: 1,
        fullName: "Lead Demo",
        email: "lead@example.com",
        phone: "0909000001",
        message: "Moi lien he demo.",
        status: "NEW",
        createdAt: stamp(),
        updatedAt: stamp(),
      },
    ],
    provinces: seedProvinces,
    wards: seedWards,
    properties: [
      {
        id: 1,
        userId: 1,
        title: "Mặt bằng Quận 1",
        slug: "mat-bang-quan-1",
        categoryId: 12,
        category: {
          id: 12,
          type: "PROPERTY",
          name: "Mặt bằng",
          slug: "mat-bang",
        },
        price: 25000000,
        priceAmount: 25,
        priceUnit: "MILLION",
        isNegotiable: false,
        area: 120,
        direction: "EAST",
        bedrooms: 0,
        bathrooms: 1,
        floors: 1,
        priorityStatus: "FREE",
        publishSource: "FREE_QUOTA",
        isBoosted: false,
        boostCount: 0,
        provinceId: 1,
        province: seedProvinces[0],
        wardId: 11,
        ward: seedWards[0],
        addressDetail: "123 Lê Lợi",
        longitude: 106.7,
        latitude: 10.8,
        contactName: "Test Customer",
        contactPhone: "0901000001",
        content: "Nội dung demo",
        viewCount: 10,
        status: "PUBLISHED",
        isFeatured: true,
        createdAt: stamp(),
        updatedAt: stamp(),
        images: [
          {
            id: 1,
            imageUrl: "/imgs/wallpaper-1.jpg",
            imagePublicId: "properties/demo/1",
            sortOrder: 1,
          },
        ],
      },
      {
        id: 2,
        userId: 1,
        title: "Văn phòng Quận 7",
        slug: "van-phong-quan-7",
        categoryId: 11,
        category: {
          id: 11,
          type: "PROPERTY",
          name: "Văn phòng",
          slug: "van-phong",
        },
        price: 40000000,
        priceAmount: 40,
        priceUnit: "MILLION",
        isNegotiable: false,
        area: 180,
        direction: "SOUTH",
        bedrooms: 0,
        bathrooms: 2,
        floors: 2,
        priorityStatus: "STANDARD",
        publishSource: "FREE_QUOTA",
        isBoosted: false,
        boostCount: 0,
        provinceId: 1,
        province: seedProvinces[0],
        wardId: 12,
        ward: seedWards[1],
        addressDetail: "456 Nguyễn Văn Linh",
        longitude: 106.72,
        latitude: 10.74,
        contactName: "Test Customer",
        contactPhone: "0901000001",
        content: "Nội dung demo 2",
        viewCount: 4,
        status: "PUBLISHED",
        isFeatured: false,
        createdAt: stamp(),
        updatedAt: stamp(),
        images: [
          {
            id: 2,
            imageUrl: "/imgs/wallpaper-2.jpg",
            imagePublicId: "properties/demo/2",
            sortOrder: 1,
          },
        ],
      },
    ],
    rentRequests: [
      {
        id: 1,
        userId: 1,
        title: "Cần thuê căn hộ Quận 1",
        slug: "can-thue-can-ho-quan-1",
        categoryId: 21,
        category: {
          id: 21,
          type: "RENT_REQUEST",
          name: "Căn hộ chung cư",
          slug: "can-ho-chung-cu",
        },
        desiredProvinceId: 1,
        desiredProvince: seedProvinces[0],
        desiredWardId: 11,
        desiredWard: seedWards[0],
        budget: 15000000,
        budgetAmount: 15,
        budgetUnit: "MILLION",
        isNegotiable: false,
        desiredArea: 75,
        bedrooms: 2,
        bathrooms: 1,
        floors: 0,
        desiredDirection: "EAST",
        requirementText: "Ưu tiên gần trung tâm.",
        contactName: "Test Customer",
        contactPhone: "0901000001",
        status: "PUBLISHED",
        isMatched: false,
        viewCount: 9,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
      {
        id: 2,
        userId: 1,
        title: "Cần thuê văn phòng Quận 7",
        slug: "can-thue-van-phong-quan-7",
        categoryId: 22,
        category: {
          id: 22,
          type: "RENT_REQUEST",
          name: "Văn phòng",
          slug: "van-phong",
        },
        desiredProvinceId: 1,
        desiredProvince: seedProvinces[0],
        desiredWardId: 12,
        desiredWard: seedWards[1],
        budget: 30000000,
        budgetAmount: 30,
        budgetUnit: "MILLION",
        isNegotiable: false,
        desiredArea: 140,
        bedrooms: 0,
        bathrooms: 1,
        floors: 1,
        desiredDirection: "SOUTH",
        requirementText: "Cần chỗ để xe.",
        contactName: "Test Customer",
        contactPhone: "0901000001",
        status: "PUBLISHED",
        isMatched: false,
        viewCount: 6,
        createdAt: stamp(),
        updatedAt: stamp(),
      },
    ],
  };
}

module.exports = {
  createInitialState,
};
